name: spkr-recog-cuda
channels:
  - defaults
dependencies:
  - python==3.11
  - cuda==12.6
  - jupyter
  - matplotlib
  - tqdm
  - pip
  - pip:
    - datasets
    - einops
    - inflect
    - librosa
    - kagglehub
    - notebook
    - numpy
    - pytorch-memlab
    - soundfile
    - tensorboard
    - torch
    - torchaudio
    - torchinfo
    - transformers
    - unidecode
    - git+https://github.com/state-spaces/mamba.git
